Q-/ Suppose the IQ in a certain population is normally distributed with a mean of Mu equal to = 100. A standard deviation of = 15. A Researchers want to know if a new drug affect IQ level, so he recruited 20 patients to try it and record their IQ level. The following code show how to perform a one simple Z-test in Python to determine if the new drugs causes a significant difference in IQ level. 

## Z-test

In [6]:
from statsmodels.stats.weightstats import ztest as ztest

In [7]:
#Enter IQ Levels for 20 patients
data = [88, 92, 94, 94, 96, 97, 97, 97, 99, 99, 105, 109, 109, 109, 110, 112, 112, 113, 114, 115 ]

In [8]:
ztest(data,value =100)
#(Ztest value = 1.5976, Pvalue = 0.1101 )

#0.11( Pvalue) < 0.05 (alpha value). - Reject the hypothesis.

(1.5976240527147705, 0.1101266701438426)

## T- test

In [10]:
ages = [10, 20, 35, 50, 28, 40, 55, 18, 16, 55, 30, 25, 43, 18, 30, 28, 14, 24, 16, 17, 32, 35, 26, 27, 65, 18, 43, 23, 21, 20, 19, 70]

In [12]:
import numpy as np
ages_mean=np.mean(ages)
ages_mean

30.34375

In [18]:
sampel_size = 10
age_sample = np.random.choice(ages,sampel_size)

In [19]:
age_sample

array([18, 19, 28, 21, 70, 14, 30, 18, 55, 20])

In [20]:
from scipy.stats import ttest_1samp

In [23]:
ttest_1samp(age_sample,30)

Ttest_1sampResult(statistic=-0.1198513786014684, pvalue=0.9072336742901175)

# Consider another example
ages of the college students(population)

#1 class student  mean of all the ages |

In [26]:
import numpy as np
import pandas as pd
import scipy.stats as ststs
import math

In [27]:
np.random.seed(6)
school_ages=ststs.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages=ststs.poisson.rvs(loc=18,mu=30,size=60)

In [29]:
school_ages

array([62, 59, 44, ..., 45, 52, 50])

In [30]:
classA_ages

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [31]:
classA_ages.mean()

46.9

In [32]:
ttest_1samp(classA_ages,school_ages.mean())

Ttest_1sampResult(statistic=-9.604796510704091, pvalue=1.139027071016194e-13)

In [33]:
school_ages.mean()

53.303333333333335

In [34]:
#rejected 